package itn

const (
	ErrorTokenRequired                        = "api.gopgserver.err.001" //"token required"
	ErrorUnknown                              = "api.gopgserver.err.002" //"something went wrong"
	ErrorUserExists                           = "api.gopgserver.err.003" //"user already exists"
	ErrorTokenInvalid                         = "api.gopgserver.err.004" //"invalid token"
	ErrorInvalidData                          = "api.gopgserver.err.005" //"invalid data"
	ErrorNameIsRequired                       = "api.gopgserver.err.006" //"name is required"
	ErrorUsernameRequired                     = "api.gopgserver.err.007" //"username is required"
	ErrorPasswordRequired                     = "api.gopgserver.err.008" //"password is required"
	ErrorUsernameNotFound                     = "api.gopgserver.err.009" //"username not found"
	ErrorInvalidPassword                      = "api.gopgserver.err.010" //"invalid password"
	ErrorFirstnameRequired                    = "api.gopgserver.err.011" //"username required"
	ErrorLastnameRequired                     = "api.gopgserver.err.012" //"lastname required"
	ErrorRoleRequired                         = "api.gopgserver.err.013" //"role is required"
	ErrorUsernameTaken                        = "api.gopgserver.err.014" //"Username already taken"
	ErrorEmailRequired                        = "api.gopgserver.err.015" //"email is required"
	ErrorTooShortUsername                     = "api.gopgserver.err.016" //"username must contain at least 3 characters"
	ErrorPasswordTooShort                     = "api.gopgserver.err.017" //"password must contain at least 8 characters"
	ErrorLoginFailed                          = "api.gopgserver.err.018" //"Verifier vos identifiants ou contacter votre administrateur"
	ErrorIdConsultationRequired               = "api.gopgserver.err.019" //"missing consultation id"
	ErrorDateRequired                         = "api.gopgserver.err.020" //"missing date"
	ErrorDurationRequired                     = "api.gopgserver.err.021" //"missing duration"
	ErrorTimeSlotOccupied                     = "api.gopgserver.err.022" //"this time slot is not free"
	ErrorAppointmentNotFound                  = "api.gopgserver.err.023" //"appointment not found"
	ErrorContactNotFound                      = "api.gopgserver.err.024" //"contact not found",
	ErrorInvalidDate                          = "api.gopgserver.err.025" //"invalid date"
	ErrorGenNameRequired                      = "api.gopgserver.err.026" //"missing generic name"
	ErrorMissingMedicineCode                  = "api.gopgserver.err.027" //"missing medicine atc code"
	ErrorPrescriptionNotFound                 = "api.gopgserver.err.028" //"prescription not found"
	ErrorDuplicateMedicineCode                = "api.gopgserver.err.029" //"duplicate  medicine  atc code"
	ErrorMedicineTypeIdRequired               = "api.gopgserver.err.030" //"medicine type is required"
	ErrorMedicineTypeNotFound                 = "api.gopgserver.err.031" //"medicine type not found"
	ErrorListTypeNotFound                     = "api.gopgserver.err.032" //"medicine list type not found"
	ErrorConsultationNotFound                 = "api.gopgserver.err.033" //"consultation not found"
	ErrorTypeSoinNotFound                     = "api.gopgserver.err.034" //"care type not found"
	ErrorBillNotFound                         = "api.gopgserver.err.035" //"bill not found"
	ErrorNoFund                               = "api.gopgserver.err.036" //"no fund"
	ErrorAnalysesNotFound                     = "api.gopgserver.err.037" //"analyses not found"
	ErrorTestNameRequired                     = "api.gopgserver.err.038" // "missing test name"
	ErrorTestCodeRequired                     = "api.gopgserver.err.039" //"missing test code"
	ErrorExaminationNotFound                  = "api.gopgserver.err.040" //"examinatiom not found"
	ErrorNoteGynecologique                    = "api.gopgserver.err.041" //"gynecological note not found"
	ErrorOrderAlreadySent                     = "api.gopgserver.err.042" //"order is already sent"
	ErrorOrderHasNotBeenSent                  = "api.gopgserver.err.043" //"order has not been sent"
	ErrorOrderResultNotFound                  = "api.gopgserver.err.044" //"result not ready"
	ErrorDateIsInvalid                        = "api.gopgserver.err.045" //"date is invalid"
	ErrorNoAccessToSilabmed                   = "api.gopgserver.err.046" //"access to silabmed is denied"
	ErrorNoAccessToSysgestock                 = "api.gopgserver.err.047" //"access to sysgestock is denied"
	ErrorCareExists                           = "api.gopgserver.err.048" //"test code already exists"
	ErrorCareNameRequired                     = "api.gopgserver.err.049" //"care name required"
	ErrorCareCodeRequired                     = "api.gopgserver.err.050" //"care code required"
	ErrorNotAuthorized                        = "api.gopgserver.err.051" //"insufficient privilege"
	ErrorCurrencyNotFound                     = "api.gopgserver.err.052" //"currency not found"
	ErrorRoleNotFound                         = "api.gopgserver.err.053" //"role not found"
	ErrorUnauthorizedOperation                = "api.gopgserver.err.054" //"unauthorized operation"
	ErrorAbbrRequired                         = "api.gopgserver.err.055" //"abbr required"
	ErrorTokenExpired                         = "api.gopgserver.err.056" //"token expired"
	ErrorUserNotFound                         = "api.gopgserver.err.057" //"user not found"
	ErrorInfoNotFound                         = "api.gopgserver.err.058" //"info not found"
	ErrorVaccinNameRequired                   = "api.gopgserver.err.059" //"vaccine name required"
	ErrorVaccinDoseRequired                   = "api.gopgserver.err.060" //"vaccine dose quantity required"
	ErrorDosageUnitRequired                   = "api.gopgserver.err.061" //"dosage unit required"
	ErrorDosageRequired                       = "api.gopgserver.err.062" //"dosage required"
	ErrorMedicineNotFound                     = "api.gopgserver.err.063" //"medicine not found"
	ErrorMaladieNotFound                      = "api.gopgserver.err.064" //"disease not found"
	ErrorDiagnosticNotFound                   = "api.gopgserver.err.065" //"diagnostic not found"
	ErrorSKURequired                          = "api.gopgserver.err.066" //"medicament sku is required"
	ErrorSuccursaleNotFound                   = "api.gopgserver.err.067" //"succursale not found"
	ErrorInvalidTypeInJSONData                = "api.gopgserver.err.068" //"invalid field type in json data"
	ErrorEmptyBody                            = "api.gopgserver.err.069" //"no data submitted"
	ErrorDiseaseCodeRequired                  = "api.gopgserver.err.070" //"disease code required"
	ErrorDeactivateSuccursale                 = "api.gopgserver.err.071" //"cannot deactivate succursale with employee"
	ErrorDoctorNotFound                       = "api.gopgserver.err.072" //"doctor not found"
	ErrorPasswordNotMatch                     = "api.gopgserver.err.073" //"password not match"
	ErrorPasswordNotStrong                    = "api.gopgserver.err.074" //"password not strong"
	ErrorCountryRequired                      = "api.gopgserver.err.075" //"country required"
	ErrorEmailInvalid                         = "api.gopgserver.err.076" //"invalid email"
	ErrorInvalidFilters                       = "api.gopgserver.err.077" // "invalid filters"
	ErrorInvalidSortParam                     = "api.gopgserver.err.078" // "invalid sort"
	ErrorAlreadyDisabled                      = "api.gopgserver.err.079" // "already disabled"
	ErrorAlreadyEnabled                       = "api.gopgserver.err.080" // "already enabled"
	ErrorOldPassIncorrect                     = "api.gopgserver.err.081" // "old password incorrect"
	ErrorContactNameRequired                  = "api.gopgserver.err.082" // "contact name required"
	ErrorProfileNotFound                      = "api.gopgserver.err.083" // "profile not found"
	ErrorProfileExists                        = "api.gopgserver.err.084" // "profile already exists"
	ErrorCurrencyRequired                     = "api.gopgserver.err.085" // "currency required"
	ErrorAccountNotVerified                   = "api.gopgserver.err.086" // "account not verified"
	ErrorInvalidRate                          = "api.gopgserver.err.087" // "invalid rate"
	ErrorCannotRateSelf                       = "api.gopgserver.err.088" // "cannot rate self"
	ErrorRateNotFound                         = "api.gopgserver.err.089" // "rate not found"
	ErrorInvalidProfileType                   = "api.gopgserver.err.090" // "invalid profile type"
	ErrorRoomNotFound                         = "api.gopgserver.err.091" // "room not found"
	ErrorMessageNotFound                      = "api.gopgserver.err.092" // "message not found"
	ErrorNotificationNotFound                 = "api.gopgserver.err.093" // "notification not found"
	ErrorPhoneRequired                        = "api.gopgserver.err.094" // "phone required"
	ErrorTitleRequired                        = "api.gopgserver.err.095" // "title required"
	ErrorMessageRequired                      = "api.gopgserver.err.096" // "message required"
	ErrorDesclaimerAcceptanceRequired         = "api.gopgserver.err.097" // "desclaimer acceptance required"
	ErrorDesclaimerIdentifierEmpty            = "api.gopgserver.err.098" // desclaimer identifier empty
	ErrorDesclaimerIdentifierExist            = "api.gopgserver.err.099" // desclaimer identifier exist
	ErrorDesclaimerNotFound                   = "api.gopgserver.err.100" // desclaimer not found
	ErrorDesclaimerNotAccepted                = "api.gopgserver.err.101" // desclaimer not accepted
	ErrorContractTypeNotFound                 = "api.gopgserver.err.102" // contract type not found
	ErrorContractTypeNameRequired             = "api.gopgserver.err.103" // contract type name required
	ErrorInvalidBase64File                    = "api.gopgserver.err.104" // invalid base64 file"
	ErrorContractTypeRequired                 = "api.gopgserver.err.105" // contract type required"
	ErrorContractNameRequired                 = "api.gopgserver.err.106" // contract name required"
	ErrorContractSignersRequired              = "api.gopgserver.err.107" // contract signers required
	ErrorRecipientNameRequired                = "api.gopgserver.err.108" // recipient name required
	ErrorRecipientEmailRequired               = "api.gopgserver.err.109" // recipient email required
	ErrorContractExpirationDateRequired       = "api.gopgserver.err.110" // contract expiration date required
	ErrorRecipientRoleRequired                = "api.gopgserver.err.111" // recipient role required
	ErrorNeedToLoginToProfile                 = "api.gopgserver.err.112" // need to login to profile
	ErrorEmailExists                          = "api.gopgserver.err.113" // email already exists
	ErrorContractNotFound                     = "api.gopgserver.err.114" // contract not found
	ErrorValueCannotBeNegative                = "api.gopgserver.err.115" // value cannot be negative
	ErrorOccupationRequired                   = "api.gopgserver.err.116" // occupation required
	ErrorContactEmailRequired                 = "api.gopgserver.err.117" // contact email required
	ErrorDuplicateSigner                      = "api.gopgserver.err.118" // duplicate signer
	ErrorDuplicateRecipient                   = "api.gopgserver.err.119" // duplicate recipient
	ErrorFileTooLarge                         = "api.gopgserver.err.120" // file too large
	ErrorContractTypeNameExist                = "api.gopgserver.err.121" // contract type name exists
	ErrorInvalidStatus                        = "api.gopgserver.err.122" // invalid status
	ErrorJobTitleRequired                     = "api.gopgserver.err.123" // invalid job title
	ErrorProfessionalDomainRequired           = "api.gopgserver.err.124" // professional domain required
	ErrorJobDescriptionRequired               = "api.gopgserver.err.125" // job description required
	ErrorJobBudgetRequired                    = "api.gopgserver.err.126" // job budget required
	ErrorJobNotFound                          = "api.gopgserver.err.127" // job not found
	ErrorCoverLetterToShort                   = "api.gopgserver.err.128" // cover letter too short
	ErrorJobClosed                            = "api.gopgserver.err.129" // job closed
	ErrorCannotChooseYourSelf                 = "api.gopgserver.err.130" // cannot choose yourself
	ErrorProfessionalNotApplied               = "api.gopgserver.err.131" // professional not applied
	ErrorSignerEmailAndNameRequired           = "api.gopgserver.err.132" // signer email and name required
	ErrorCurrencyExists                       = "api.gopgserver.err.133" // currency already exists
	ClientNotConnected                        = "api.gopgserver.err.134" // client not connected
	ErrorProfessionRequired                   = "api.gopgserver.err.135" // profession required
	ErrorProfessionInvalid                    = "api.gopgserver.err.136" // profession invalid
	ErrorRepresentativeIdRequired             = "api.gopgserver.err.137" // representative id required
	ErrorRepresentativeNotFound               = "api.gopgserver.err.138" // representative not found
	ErrorInvalidRole                          = "api.gopgserver.err.139" // invalid role
	ErrorClientAlreadyConnected               = "api.gopgserver.err.140" // client already connected
	ErrorNoAssignedRepresentative             = "api.gopgserver.err.141" // no assigned representative
	ErrorProfessionNeeded                     = "api.gopgserver.err.142" // profession needed
	ErrorInvalidImage                         = "api.gopgserver.err.143" // invalid image
	ErrorIPHidden                             = "api.gopgserver.err.144" // ip hidden
	ErrorEntityIDRequired                     = "api.gopgserver.err.145" // entity id required in upload file
	ErrorEntityRequired                       = "api.gopgserver.err.146" // entity required in upload file
	ErrorFileNameRequired                     = "api.gopgserver.err.147" // file name required
	ErrorInvalidEntity                        = "api.gopgserver.err.148" // invalid entity
	ErrorKeyRequired                          = "api.gopgserver.err.149" // key required
	ErrorFileTypeRequired                     = "api.gopgserver.err.150" // file type required
	ErrorFileNotFound                         = "api.gopgserver.err.151" // file not found
	ErrorInvalidFileType                      = "api.gopgserver.err.152" // invalid file type
	ErrorFileAlreadyExists                    = "api.gopgserver.err.153" // file already exists
	ErrorNoteContentRequired                  = "api.gopgserver.err.154" // note content required
	ErrorNoteTitleRequired                    = "api.gopgserver.err.155" // note title required
	ErrorInvalidAuthorizedParty               = "api.gopgserver.err.156" // invalid authorized party
	ErrorEmptyKey                             = "api.gopgserver.err.157" // key of file is empty
	ErrorUnsupportedFile                      = "api.gopgserver.err.158" // unsupported file type
	ErrorNoteNotFound                         = "api.gopgserver.err.159" // note not found
	ErrorOwnerNameRequired                    = "api.gopgserver.err.160" // owner name required
	ErrorOwnerTypeRequired                    = "api.gopgserver.err.161" // owner type required
	ErrorOwnerTypeInvalid                     = "api.gopgserver.err.162" // owner type invalid
	ErrorOwnerEquityInvalid                   = "api.gopgserver.err.163" // owner equity invalid
	ErrorOwnerEquitySumInvalid                = "api.gopgserver.err.164" // owner equity sum invalid
	ErrorFilesLimitReached                    = "api.gopgserver.err.165" // files limit reached
	ErrorNoRepresentativeAvailable            = "api.gopgserver.err.166" // no representative available
	ErrorFileSizeExceed                       = "api.gopgserver.err.167" // file size limit exceed
	InvalidSubInterestFormat                  = "api.gopgserver.err.168" // invalid subinterest format
	ErrorUnknownMediaType                     = "api.gopgserver.err.169" // invalid media type format
	ErrorWorkflowNameRequired                 = "api.gopgserver.err.170" // invalid workflow name format
	ErrorUnknownWorkflowCategory              = "api.gopgserver.err.171" // invalid work flow category
	ErrorUnknownWorkflowNodeType              = "api.gopgserver.err.172" // invalid work flow node type
	ErrorWorkflowNodeWorkflowIdRequired       = "api.gopgserver.err.173" // work flow id required
	ErrorWorkflowNodePositionRequired         = "api.gopgserver.err.174" // workflow node position required
	ErrorWorkflowNodeRequired                 = "api.gopgserver.err.175" // work flow node required
	ErrorWorkflowNodeRuleTypeRequired         = "api.gopgserver.err.176" // work flow node rule type required
	ErrorUnknownWorkflowNodeRuleType          = "api.gopgserver.err.177" // invalid work flow node rule type
	ErrorWorkflowNodeRuleNameRequired         = "api.gopgserver.err.178" // work flow node rule name required
	ErrorWorkflowNodeRuleNodeIdRequired       = "api.gopgserver.err.179" // work flow node rule parent node id required
	ErrorUnknownWorkflowNodeRuleTimeReference = "api.gopgserver.err.180" // invalid work flow node rule type
	ErrorWorkflowNodeRuleActionTypeRequired   = "api.gopgserver.err.181" // work flow node rule parent node id required
	ErrorUnknownWorkflowNodeRuleActionType    = "api.gopgserver.err.182" // invalid work flow node rule type
	ErrorCreatingPartnerProfile               = "api.gopgserver.err.183" // error creating partner profile
	ErrorInvalidBuyerType                     = "api.gopgserver.err.184" // Buyer type did not matched
	ErrorGetingSellerProfile                  = "api.gopgserver.err.185" // error getting seller Profile
	ProfessionaNotExist                       = "api.gopgserver.err.186" // Profession does not exist
)
